### ISSUE TITLE
Use Item Keybind Detection

### ISSUE THREAD

**Issue by HeroMotion677** [infernalexp/Shield-Expansion#12]
Shield use detects key press of right click instead of the keybind use item. Using shield while use item is different key does not work. (example of switching left and right click)

**Comment by Dariensg** [comment]
(This was my guess of what is happening, not necessarily what is actually happening. Glancing quickly at the code, I'm not actually certain this is what's causing it.)

**Comment by HeroMotion677** [comment]
> 

Hm, that's wild. This is a very strange bug it seems

**Comment by tinytransfem** [comment]
Yeah no, that's not what's happening - what IS happening though is that our attacking out of blocking mechanic is based on a client-side check for whether the left mouse button is pressed in order to cancel the blocking state. I used this because there is no event hook for when a player attempts to attack, only for when they have already attacked. I'll have to research whether there is something similar that triggers when the attack button in general is pressed. If there isn't, I have no idea how to fix this...

Either way, thanks for bringing this to my attention!

**Comment by tinytransfem** [comment]
This has been fixed in version 1.0.4
